import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeft, Download, Printer, CheckCircle, XCircle } from 'lucide-react';
import * as billService from '../services/billService';
import { useAuth } from '../contexts/AuthContext';

const BillDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [bill, setBill] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetch = async () => {
      try {
        const res = await billService.getBill(id);
        setBill(res.data.data);
      } catch {
        toast.error('Invoice not found');
        navigate('/bills');
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [id, navigate]);

  const handleStatus = async (status) => {
    try {
      await billService.updateBillStatus(id, status);
      setBill((prev) => ({ ...prev, status }));
      toast.success(`Invoice marked as ${status}`);
    } catch {
      toast.error('Status update failed');
    }
  };

  const handlePrint = () => window.print();

  const statusBadge = (status) => {
    const colors = {
      paid: 'bg-blue-100 text-blue-700',
      unpaid: 'bg-gray-100 text-gray-700',
      cancelled: 'bg-gray-100 text-gray-700',
    };
    return (
      <span className={`px-3 py-1 text-sm font-medium rounded-full ${colors[status] || 'bg-gray-100 text-gray-600'}`}>
        {status?.charAt(0).toUpperCase() + status?.slice(1) || 'Unknown'}
      </span>
    );
  };

  if (loading) {
    return (
      <div className="flex justify-center py-20">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-600" />
      </div>
    );
  }

  if (!bill) return null;

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6">
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between mb-6 print:hidden">
        <button onClick={() => navigate('/bills')}
          className="flex items-center gap-2 px-3 py-2 text-gray-600 hover:bg-gray-100 rounded-lg text-sm">
          <ArrowLeft size={18} /> Back to Invoices
        </button>
        <div className="flex flex-wrap items-center gap-2">
          <button onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium text-gray-700">
            <Printer size={16} /> Print
          </button>
          <button onClick={() => handleStatus('paid')}
            className="flex items-center gap-1.5 px-3 py-2 bg-blue-100 hover:bg-blue-200 rounded-lg text-sm font-medium text-blue-700">
            <CheckCircle size={16} /> Mark Paid
          </button>
          <button onClick={() => handleStatus('cancelled')}
            className="flex items-center gap-1.5 px-3 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium text-gray-700">
            <XCircle size={16} /> Cancel
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="p-8">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-6">
            <div>
              <h1 className="text-2xl font-bold text-gray-800">INVOICE</h1>
              <p className="text-sm text-gray-500 mt-1">#{bill.billNumber}</p>
            </div>
            <div className="text-left sm:text-right">
              <p className="text-lg font-bold text-blue-600">StockHub Ltd</p>
              <p className="text-sm text-gray-500">Kigali City, Rwanda</p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
            <div>
              <p className="text-sm text-gray-500">Invoice Date</p>
              <p className="font-medium">{new Date(bill.createdAt).toLocaleDateString()}</p>
            </div>
            <div>{statusBadge(bill.status)}</div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8 p-4 bg-gray-50 rounded-lg">
            <div>
              <p className="text-sm text-gray-500 mb-1">Bill To</p>
              <p className="font-semibold text-gray-800">{bill.customerName}</p>
              {bill.customerContact && (
                <p className="text-sm text-gray-600">{bill.customerContact}</p>
              )}
            </div>
            <div className="text-left md:text-right">
              <p className="text-sm text-gray-500 mb-1">Generated By</p>
              <p className="font-semibold text-gray-800">{bill.generatedBy?.username || 'System'}</p>
            </div>
          </div>

          <div className="overflow-x-auto rounded-lg border border-gray-200 mb-8">
            <table className="min-w-full">
              <thead>
                <tr className="border-b-2 border-gray-200">
                  <th className="py-3 text-left text-sm font-semibold text-gray-700">#</th>
                  <th className="py-3 text-left text-sm font-semibold text-gray-700">Product</th>
                  <th className="py-3 text-left text-sm font-semibold text-gray-700">Code</th>
                  <th className="py-3 text-right text-sm font-semibold text-gray-700">Qty</th>
                  <th className="py-3 text-right text-sm font-semibold text-gray-700">Unit Price</th>
                  <th className="py-3 text-right text-sm font-semibold text-gray-700">Total</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {bill.items.map((item, idx) => (
                  <tr key={idx}>
                    <td className="py-3 text-sm text-gray-600">{idx + 1}</td>
                    <td className="py-3 text-sm font-medium text-gray-800">{item.productName}</td>
                    <td className="py-3 text-sm text-gray-600">{item.productCode}</td>
                    <td className="py-3 text-sm text-right text-gray-600">{item.quantity}</td>
                    <td className="py-3 text-sm text-right text-gray-600">{Number(item.unitPrice).toLocaleString()} Frw</td>
                    <td className="py-3 text-sm text-right font-medium text-gray-800">{Number(item.totalPrice).toLocaleString()} Frw</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm text-gray-600">
                <span>Subtotal</span>
                <span>{Number(bill.subtotal).toLocaleString()} Frw</span>
              </div>
              <div className="flex justify-between text-sm text-gray-600">
                <span>Tax</span>
                <span>{Number(bill.tax).toLocaleString()} Frw</span>
              </div>
              <div className="flex justify-between text-lg font-bold text-gray-800 border-t-2 border-gray-200 pt-2">
                <span>Total</span>
                <span>{Number(bill.totalAmount).toLocaleString()} Frw</span>
              </div>
            </div>
          </div>

          {bill.notes && (
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-500 mb-1">Notes</p>
              <p className="text-sm text-gray-700">{bill.notes}</p>
            </div>
          )}

          <div className="mt-8 text-center text-xs text-gray-400 border-t border-gray-100 pt-4">
            <p>StockHub Ltd &bull; Kigali City, Rwanda</p>
            <p>Invoice #{bill.billNumber} &bull; Generated on {new Date(bill.createdAt).toLocaleString()}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BillDetail;
