import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../contexts/ToastContext';
import reportService from '../services/reportService';
import { FileText, Download, Printer } from 'lucide-react';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function Reports() {
  const { user } = useAuth();
  const { addToast } = useToast();
  const [reportType, setReportType] = useState('sales');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);

  const fetchReport = useCallback(async () => {
    setLoading(true);
    try {
      const res = await reportService.getReport(reportType, startDate, endDate);
      if (res.data.success) setReportData(res.data.data);
    } catch {
      addToast('Failed to generate report', 'error');
    } finally {
      setLoading(false);
    }
  }, [reportType, startDate, endDate, addToast]);

  useEffect(() => {
    if (reportType) fetchReport();
  }, [reportType, fetchReport]);

  const getHeadersForType = () => {
    switch (reportType) {
      case 'customers':
        return [['Number', 'First Name', 'Last Name', 'Telephone', 'Address']];
      case 'products':
        return [['Code', 'Name', 'Qty Sold', 'Unit Price', 'Total Value']];
      case 'sales':
      default:
        return [['Invoice', 'Customer', 'Date', 'Payment', 'Total']];
    }
  };

  const mapRecordToArray = (record) => {
    switch (reportType) {
      case 'customers':
        return [
          record.customerNumber,
          record.firstName,
          record.lastName,
          record.telephone,
          record.address,
        ];
      case 'products':
        return [
          record.productCode,
          record.productName,
          record.quantitySold,
          record.unitPrice,
          record.quantitySold * record.unitPrice,
        ];
      case 'sales':
      default:
        return [
          record.invoiceNumber,
          record.customer
            ? `${record.customer.firstName || ''} ${record.customer.lastName || ''}`
            : 'N/A',
          new Date(record.salesDate).toLocaleDateString(),
          record.paymentMethod,
          record.totalAmountPaid,
        ];
    }
  };

  const exportCSV = () => {
    if (!reportData?.records?.length) {
      addToast('No data to export', 'error');
      return;
    }
    const headers = getHeadersForType()[0];
    const rows = reportData.records.map(mapRecordToArray);
    const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${reportType}_report_${Date.now()}.csv`;
    link.click();
    addToast('CSV exported', 'success');
  };

  const exportExcel = () => {
    if (!reportData?.records?.length) {
      addToast('No data to export', 'error');
      return;
    }
    const headers = getHeadersForType()[0];
    const rows = reportData.records.map(mapRecordToArray);
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, reportType);
    XLSX.writeFile(wb, `${reportType}_report_${Date.now()}.xlsx`);
    addToast('Excel exported', 'success');
  };

  const exportPDF = () => {
    if (!reportData?.records?.length) {
      addToast('No data to export', 'error');
      return;
    }
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SalesPro Ltd', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Huye District, Southern Province, Rwanda', pageWidth / 2, 26, { align: 'center' });
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(reportData.title || `${reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report`, pageWidth / 2, 34, { align: 'center' });

    // Metadata
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report ID: ${reportData.reportId}`, 14, 42);
    doc.text(`Generated By: ${reportData.generatedBy || user?.username}`, 14, 47);
    doc.text(`Generated At: ${new Date(reportData.generatedAt).toLocaleString()}`, 14, 52);

    // Table
    const headers = getHeadersForType()[0];
    const rows = reportData.records.map(mapRecordToArray);

    doc.autoTable({
      startY: 58,
      head: [headers],
      body: rows,
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [79, 70, 229] },
      didDrawPage: (data) => {
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.setFontSize(7);
          doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' });
        }
      },
    });

    doc.save(`${reportType}_report_${Date.now()}.pdf`);
    addToast('PDF exported', 'success');
  };

  const handlePrint = () => {
    window.print();
  };

  const typeLabels = {
    customers: 'Customer Report',
    products: 'Product Report',
    sales: 'Sales Report',
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-white">Reports</h1>
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-600 p-5 mb-6">
        <div className="flex flex-wrap gap-4 items-end">
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">Report Type</label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
            >
              <option value="sales">Sales Report</option>
              <option value="customers">Customer Report</option>
              <option value="products">Product Report</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">Start Date</label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-1">End Date</label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="px-3 py-2 bg-slate-700 border border-slate-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-primary-500 text-sm"
            />
          </div>
          <button onClick={fetchReport} className="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg text-sm transition-colors">
            Generate
          </button>
        </div>
      </div>

      {reportData && (
        <div className="bg-slate-800 rounded-xl border border-slate-600 p-5">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="text-lg font-semibold text-white">{typeLabels[reportType] || 'Report'}</h2>
              <p className="text-xs text-slate-400 mt-1">
                Report ID: {reportData.reportId} | Generated by: {reportData.generatedBy || user?.username} |{' '}
                {reportData.totalRecords} records
              </p>
            </div>
            <div className="flex gap-2">
              <button onClick={exportCSV} className="flex items-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg text-xs transition-colors">
                <Download className="w-3.5 h-3.5" /> CSV
              </button>
              <button onClick={exportExcel} className="flex items-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg text-xs transition-colors">
                <Download className="w-3.5 h-3.5" /> Excel
              </button>
              <button onClick={exportPDF} className="flex items-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg text-xs transition-colors">
                <FileText className="w-3.5 h-3.5" /> PDF
              </button>
              <button onClick={handlePrint} className="flex items-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg text-xs transition-colors">
                <Printer className="w-3.5 h-3.5" /> Print
              </button>
            </div>
          </div>

          {loading ? (
            <div className="space-y-2">
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="h-8 bg-slate-700 animate-pulse rounded" />
              ))}
            </div>
          ) : reportData.records?.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead>
                  <tr className="border-b border-slate-600">
                    {getHeadersForType()[0].map((h) => (
                      <th key={h} className="px-3 py-2 text-slate-300 font-medium">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {reportData.records.map((record, idx) => (
                    <tr key={record._id || idx} className="border-b border-slate-700 hover:bg-slate-700/50">
                      {mapRecordToArray(record).map((val, i) => (
                        <td key={i} className="px-3 py-2 text-slate-200">
                          {typeof val === 'number' && reportType !== 'customers'
                            ? `FRW ${Number(val).toLocaleString()}`
                            : val}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="text-center text-slate-400 py-8">No records found for the selected criteria</p>
          )}
        </div>
      )}
    </div>
  );
}
