import { useState, useCallback } from 'react';
import { getDailySalesReport, getDailyStockReport, exportReport } from '../services/reportService';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../components/Toast';
import { FileText, Download, Printer, FileSpreadsheet, File as FilePdf } from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function Reports() {
  const { user } = useAuth();
  const { addToast } = useToast();
  const [activeTab, setActiveTab] = useState('sales');
  const [dateRange, setDateRange] = useState({
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
  });
  const [reportData, setReportData] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  const loadSalesReport = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getDailySalesReport(dateRange.startDate, dateRange.endDate);
      if (res.success) {
        setReportData(res.data.reportData || []);
        setSummary(res.data.summary);
      }
    } catch {
      addToast('Failed to load sales report', 'error');
    } finally {
      setLoading(false);
    }
  }, [dateRange, addToast]);

  const loadStockReport = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getDailyStockReport();
      if (res.success) {
        setReportData(res.data || []);
        setSummary(null);
      }
    } catch {
      addToast('Failed to load stock report', 'error');
    } finally {
      setLoading(false);
    }
  }, [addToast]);

  const handleGenerate = () => {
    if (activeTab === 'sales') loadSalesReport();
    else loadStockReport();
  };

  const exportCSV = async () => {
    try {
      const res = await exportReport(activeTab, 'csv', dateRange.startDate, dateRange.endDate);
      const blob = new Blob([res], { type: 'text/csv' });
      downloadBlob(blob, `${activeTab}_report.csv`);
      addToast('CSV exported successfully', 'success');
    } catch {
      addToast('Export failed', 'error');
    }
  };

  const exportExcel = () => {
    if (!reportData.length) { addToast('No data to export', 'warning'); return; }
    const ws = XLSX.utils.json_to_sheet(reportData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, activeTab === 'sales' ? 'Sales' : 'Stock');
    XLSX.writeFile(wb, `${activeTab}_report.xlsx`);
    addToast('Excel exported successfully', 'success');
  };

  const exportPDF = () => {
    if (!reportData.length) { addToast('No data to export', 'warning'); return; }
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString();

    doc.setFontSize(16).setFont('helvetica', 'bold');
    doc.text('DAB Enterprise Ltd', 14, 20);
    doc.setFontSize(10).setFont('helvetica', 'normal');
    doc.text('Kigali City, Rwanda', 14, 27);
    doc.setFontSize(12).setFont('helvetica', 'bold');
    const title = activeTab === 'sales' ? 'Daily Sales Report' : 'Daily Stock Status Report';
    doc.text(title, 14, 36);
    doc.setFontSize(8).setFont('helvetica', 'normal');
    doc.text(`Report ID: BWS-${Date.now()}`, 14, 43);
    doc.text(`Generated By: ${user?.username || 'Admin'}`, 14, 48);
    doc.text(`Date: ${dateStr}`, 14, 53);

    const headers = Object.keys(reportData[0] || {});
    const body = reportData.map((row) => headers.map((h) => String(row[h] ?? '')));

    doc.autoTable({
      startY: 58,
      head: [headers],
      body,
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [79, 70, 229] },
    });

    const finalY = doc.lastAutoTable.finalY || 58;
    doc.setFontSize(8).setFont('helvetica', 'normal');
    doc.text(`Page 1 | DAB Enterprise Ltd - Business Web Solution`, 14, finalY + 15);

    doc.save(`${activeTab}_report.pdf`);
    addToast('PDF exported successfully', 'success');
  };

  const handlePrint = () => {
    if (!reportData.length) { addToast('No data to print', 'warning'); return; }
    const win = window.open('', '_blank');
    if (!win) { addToast('Please allow popups for printing', 'error'); return; }

    const headers = Object.keys(reportData[0] || {});
    const rows = reportData.map((row) =>
      `<tr>${headers.map((h) => `<td style="border:1px solid #ddd;padding:6px;text-align:left">${row[h] ?? ''}</td>`).join('')}</tr>`
    ).join('');

    win.document.write(`
      <html><head><title>${title}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px}
      h1{color:#1e40af} table{border-collapse:collapse;width:100%;font-size:12px}
      th{background:#4f46e5;color:white;padding:8px;text-align:left}
      .footer{text-align:center;font-size:10px;color:#888;margin-top:30px}
      </style></head><body>
      <h1>DAB Enterprise Ltd</h1>
      <p>Kigali City, Rwanda</p>
      <h2>${title}</h2>
      <p>Report ID: BWS-${Date.now()} | Generated By: ${user?.username || 'Admin'} | Date: ${dateStr}</p>
      <table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>
      <div class="footer"><p>DAB Enterprise Ltd - Business Web Solution</p></div>
      <script>window.print();window.close();</script>
      </body></html>
    `);
    win.document.close();
  };

  const downloadBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs = [
    { id: 'sales', label: 'Daily Sales Report', icon: FileText },
    { id: 'stock', label: 'Daily Stock Status', icon: FileText },
  ];

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-800">Reports</h1>
        <p className="text-sm text-gray-500 mt-1">Generate and export business reports</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100">
        <div className="border-b border-gray-200 px-6">
          <div className="flex space-x-1">
            {tabs.map((tab) => (
              <button key={tab.id} onClick={() => { setActiveTab(tab.id); setReportData([]); setSummary(null); }}
                className={`flex items-center space-x-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors
                  ${activeTab === tab.id ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
              >
                <tab.icon size={16} />
                <span>{tab.label}</span>
              </button>
            ))}
          </div>
        </div>

        <div className="p-6">
          {activeTab === 'sales' && (
            <div className="flex items-end space-x-4 mb-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                <input type="date" value={dateRange.startDate}
                  onChange={(e) => setDateRange({ ...dateRange, startDate: e.target.value })}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                <input type="date" value={dateRange.endDate}
                  onChange={(e) => setDateRange({ ...dateRange, endDate: e.target.value })}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <button onClick={handleGenerate} disabled={loading}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50"
              >{loading ? 'Generating...' : 'Generate Report'}</button>
            </div>
          )}

          {activeTab === 'stock' && (
            <button onClick={handleGenerate} disabled={loading}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50 mb-6"
            >{loading ? 'Generating...' : 'Generate Stock Report'}</button>
          )}

          {summary && (
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
              <div className="bg-blue-50 rounded-xl p-4">
                <p className="text-sm text-gray-500">Total Transactions</p>
                <p className="text-2xl font-bold text-blue-600">{summary.totalSales}</p>
              </div>
              <div className="bg-green-50 rounded-xl p-4">
                <p className="text-sm text-gray-500">Total Items Sold</p>
                <p className="text-2xl font-bold text-green-600">{summary.totalItems}</p>
              </div>
              <div className="bg-orange-50 rounded-xl p-4">
                <p className="text-sm text-gray-500">Total Revenue</p>
                <p className="text-2xl font-bold text-orange-600">{summary.totalRevenue?.toLocaleString()} RWF</p>
              </div>
            </div>
          )}

          {reportData.length > 0 && (
            <>
              <div className="flex flex-wrap gap-2 mb-4">
                <button onClick={exportCSV}
                  className="flex items-center space-x-1 px-3 py-1.5 border border-gray-300 rounded-lg text-xs font-medium text-gray-600 hover:bg-gray-50"
                ><Download size={14} /><span>CSV</span></button>
                <button onClick={exportExcel}
                  className="flex items-center space-x-1 px-3 py-1.5 border border-gray-300 rounded-lg text-xs font-medium text-green-600 hover:bg-green-50"
                ><FileSpreadsheet size={14} /><span>Excel</span></button>
                <button onClick={exportPDF}
                  className="flex items-center space-x-1 px-3 py-1.5 border border-gray-300 rounded-lg text-xs font-medium text-red-600 hover:bg-red-50"
                ><FilePdf size={14} /><span>PDF</span></button>
                <button onClick={handlePrint}
                  className="flex items-center space-x-1 px-3 py-1.5 border border-gray-300 rounded-lg text-xs font-medium text-purple-600 hover:bg-purple-50"
                ><Printer size={14} /><span>Print</span></button>
              </div>

              <div className="overflow-x-auto rounded-lg border border-gray-200">
                <table className="w-full text-sm">
                  <thead className="bg-gray-50 border-b border-gray-200">
                    <tr>
                      {Object.keys(reportData[0]).map((key) => (
                        <th key={key} className="px-4 py-3 text-left font-semibold text-gray-600 whitespace-nowrap">{key}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {reportData.map((row, i) => (
                      <tr key={i} className="hover:bg-gray-50">
                        {Object.values(row).map((val, j) => (
                          <td key={j} className="px-4 py-3 text-gray-700 whitespace-nowrap">{String(val ?? '')}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )}

          {reportData.length === 0 && !loading && (
            <div className="text-center py-12 text-gray-400">
              <FileText size={40} className="mx-auto mb-3 opacity-40" />
              <p>Generate a report to view data</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
