const PDFDocument = require('pdfkit');

const generatePDF = (data, title, res, user) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/\s+/g, '_')}.pdf"`);
  doc.pipe(res);

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  doc.fontSize(18).font('Helvetica-Bold').text('DAB Enterprise Ltd', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('Kigali City, Rwanda', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica-Bold').text(title, { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(9).font('Helvetica').text(`Report ID: BWS-${Date.now()}`, { align: 'left' });
  doc.text(`Generated By: ${user?.username || 'Admin'}`, { align: 'left' });
  doc.text(`Date: ${dateStr}`, { align: 'left' });
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const colWidths = [150, 80, 80, 80];
  const headers = Object.keys(data[0] || {});

  doc.font('Helvetica-Bold').fontSize(9);
  let xPos = 40;
  headers.forEach((h, i) => {
    doc.text(h.replace(/([A-Z])/g, ' $1').trim(), xPos, tableTop, {
      width: colWidths[i] || 100, align: 'left',
    });
    xPos += colWidths[i] || 100;
  });

  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(8);
  let yPos = doc.y;
  data.forEach((row, ri) => {
    xPos = 40;
    if (yPos > 750) {
      doc.addPage();
      yPos = 40;
    }
    headers.forEach((h, i) => {
      doc.text(String(row[h] ?? ''), xPos, yPos, {
        width: colWidths[i] || 100, align: 'left',
      });
      xPos += colWidths[i] || 100;
    });
    yPos += 15;
  });

  doc.moveDown(1);
  const footerY = Math.max(doc.y, 700);
  doc.fontSize(8).font('Helvetica').text(
    `Page ${doc.bufferedPageRange().start + 1} | DAB Enterprise Ltd - Business Web Solution`,
    40, 780, { align: 'center', width: 500 }
  );

  doc.end();
};

const generateCSV = (data) => {
  if (!data.length) return '';
  const headers = Object.keys(data[0]);
  const rows = data.map((row) =>
    headers.map((h) => `"${String(row[h] ?? '').replace(/"/g, '""')}"`).join(',')
  );
  return [headers.join(','), ...rows].join('\n');
};

module.exports = { generatePDF, generateCSV };
